config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :tag_strings
  get '/posts/filter/:id' => 'posts#filter', as: "post_filter"
  root to: 'posts#index'
end

app/models/post.rb
# Post model
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tag_strings

  validates :title, presence: true
  validates :body, presence: true
  validates :author, presence: true
end

app/models/tag_string.rb
# Tags model
class TagString < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
# Posts controller
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(updated_at: :desc)
    @tags = TagString
      .select('tag_strings.name')
      .joins(:posts)
      .group('tag_strings.name')
      .order('count(tag_strings.name) desc')
  end

  def filter
    @post = Post
      .includes(:tag_strings)
      .where(tag_strings: { name: params[:id] })
      .order(updated_at: :desc)
    @posts = []
    @post.each do |posty|
      @posts << Post.find(posty[:id])
    end
    @tags = TagString
      .select('tag_strings.name')
      .joins(:posts)
      .group('tag_strings.name')
      .order('count(tag_strings.name) desc')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @tags = @post.tag_strings.map(&:name).join(', ')
  end

  # POST /posts
  # POST /posts.json
  def create
    respond_to do |format|
      @post = Post.new(post_params)
      string_tags = params[:post][:tag_strings].split(/ *[, ] */).uniq
      if string_tags.empty? || string_tags.include?(' ')
        error_tag(format, 'new', 'tag')
      elsif @post.save
        create_post(format, string_tags)
      else
        error_tag(format, 'new')
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      string_tags = params[:post][:tag_strings].split(/ *[, ] */).uniq
      if string_tags.empty? || string_tags.include?(' ')
        error_tag(format, 'edit', 'tag')
      elsif @post.update(post_params)
        update_post(format, string_tags)
      else
        error_tag(format, 'edit')
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    existing_tags = @post.tag_strings
    existing_tags.each do |tag|
      edit_tag(tag.id)
    end
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Control existing tag or create new and assign to post
  def insert_tags(string_tags)
    string_tags.each do |tag|
      curr_tag = TagString.where(name: tag)
      if curr_tag.blank?
        @post.tag_strings.create(name: tag)
      else
        @post.tag_strings << curr_tag
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow
  # the white list through.
  def post_params
    params.require(:post).permit(:author, :title, :body, tag_string_ids: [])
  end

  def edit_tag(tag_id)
    is_exist = false
    Post.all.each do |curr_post|
      is_exist = true if curr_post.tag_strings.map(&:id).include?(tag_id) &&
          @post[:id] != curr_post[:id]
    end
    TagString.find(tag_id).destroy unless is_exist
  end

  # Set error messages
  def error_tag(format, status, msg = 'standard')
    @post.errors.add(:tag_strings, 'must have at least one tag') if msg == 'tag'
    if status == 'new'
      format.html { render :new }
    else
      format.html { render :edit }
    end
    format.json { render json: @post.errors, status: :unprocessable_entity }
  end

  def update_post(format, string_tags)
    @post.tag_strings.delete
    string_tags.each do |tag|
      TagString.new(name: tag).save if TagString.where(name: tag).empty?
    end
    @post.tag_strings = TagString.where(name: string_tags)
    @post.touch
    @post.save
    format.html { redirect_to @post, notice: 'Post was successfully updated.' }
    format.json { render :show, status: :ok, location: @post }
  end

  def create_post(format, string_tags)
    insert_tags(string_tags)
    format.html { redirect_to @post, notice: 'Post was successfully created.' }
    format.json { render :show, status: :created, location: @post }
  end
end

app/helpers/application_helper.rb
# Application helper
module ApplicationHelper
end

app/helpers/posts_helper.rb
# Post helper
module PostsHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? "success" : "error"}" 
    a.close[data-dismiss="alert"]
      | ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 2.3
.navbar
  .navbar-inner
    .container
      a.btn.btn-navbar[data-toggle="collapse" data-target=".nav-collapse"]
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .nav-collapse.collapse
        .navbar.navbar-fixed-top
          nav.navbar-inner
            ul.nav
              li
                = link_to 'Home', root_path
              li
                = link_to 'New Post', new_post_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Ruby Rails Hw1 V3'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Ruby Rails Hw1 V3'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    / application layout styled for Bootstrap 2.3
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        .content
          .row
            .span12
              == render 'layouts/messages'
              == yield
          footer

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :author
    = f.text_field :author, :id => 'post_author'
  .field
    = f.label :title
    = f.text_field :title, :id => 'post_title'
  .field
    = f.label :tag_strings
    = f.text_field :tag_strings, :value => @post.tag_strings.map {|c| c.name}.join(', '), :id => 'post_tags_string'
  .field
    = f.label :body
    = f.text_area :body, :id => 'post_body'
  .actions = f.submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/filter.html.slim
= render :template => 'posts/index'

app/views/posts/index.html.slim
h1 Posts

- @tags.each do |tag|
  = link_to "#{tag.name}", post_filter_path(tag.name), :class => "filter-by-tag"

table
  thead
    tr
      th Author
      th Title
      th Body
      th Tags
      th
      th

  tbody
    - @posts.each do |post|
      tr id = "post-row-#{post.id}"
        td class="post-author" = post.author
        td class="post-title" = post.title
        td class="post-body" = post.body
        td class="post-tags" = post.tag_strings.map {|c| c.name}.join(', ')
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

br

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Author:
  = @post.author
p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body

p
  strong Tags:
  = @post.tag_strings.map {|c| c.name}.join(', ')

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path